### ISSUE TITLE
output_log.txt contains no player data for 1678.727490

### ISSUE THREAD

**Issue by vpavkin** [Manuel-777/MTG-Arena-Tool#565]
Hello!
Just updated my client to 1678.727490 and tracker doesn't startup anymore, printing

```
output_log.txt contains no player data
```

Shell log (running ubuntu 18.04)
```
linux
Checking for update
Uncaught exception;
TypeError: updaterWindow.moveTop is not a function
    at WebContents.<anonymous> (/tmp/.mount_MTG-ArM5eWPJ/resources/app.asar/main.js:81:19)
    at WebContents.emit (events.js:199:15)
Update for version 2.9.2 is not available (latest version: 2.8.7, downgrade is allowed).
Update not available { version: '2.8.7',
  files:
   [ { url: 'MTG-Arena-Tool-2.8.7.AppImage',
       sha512:
        '+dwN7KTjRmhIPVQKocCd3lr1fmckH7pYURbJSSoEwzd21qO/vMqQrensaKqaD+dsQV1Pd1YuEw1ljfKgWFsAfA==',
       size: 96339638,
       blockMapSize: 102394 } ],
  path: 'MTG-Arena-Tool-2.8.7.AppImage',
  sha512:
   '+dwN7KTjRmhIPVQKocCd3lr1fmckH7pYURbJSSoEwzd21qO/vMqQrensaKqaD+dsQV1Pd1YuEw1ljfKgWFsAfA==',
  releaseDate: '2019-08-01T23:50:18.508Z',
  releaseName: 'v2.8.7',
  releaseNotes:
   '<p>Windows installer: <code>.exe</code><br>\nLinux installer: <code>.AppImage</code><br>\nMac installer: <code>.pkg</code></p>\n<ul>\n<li>Fixed loading bug after receiving planecation land rewards</li>\n</ul>\n<p><a href="https://mtgatool.com/release-notes/" rel="nofollow">Release notes</a><br>\n<a href="https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/CHANGELOG.md">Commit changelog</a></p>' }
checkForUpdatesAndNotify called, downloadPromise is null
MAIN:  Initializing
Uncaught exception;
TypeError: overlay.moveTop is not a function
    at showWindow (/tmp/.mount_MTG-ArM5eWPJ/resources/app.asar/main.js:439:18)
    at initialize (/tmp/.mount_MTG-ArM5eWPJ/resources/app.asar/main.js:331:22)
    at EventEmitter.<anonymous> (/tmp/.mount_MTG-ArM5eWPJ/resources/app.asar/main.js:182:9)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (/tmp/.mount_MTG-ArM5eWPJ/resources/electron.asar/browser/api/web-contents.js:390:13)
    at WebContents.emit (events.js:194:13)
IPC LOG:  SEND >> 0, get_database_version, WvR0j0, undefined
IPC LOG:  RECV << 0, get_database_version, {"latest":14,"updated":1567387464702,"size":2058327}
IPC LOG:  httpAsync: 
```

**Comment by vpavkin** [comment]
Looks like it's working with 2.9.3, huge thanks for such quick fixes :+1: .
For some reason overlay shortcuts aren't working now, but it's minor. Feel free to close when a stable release is out.

Thank you!

**Comment by Manuel-777** [comment]
Closing, shortcuts can be configured in settigns now please feel free to open an issue if theres any problem with that!
