### ISSUE TITLE
Always stuck on "Loading" Just a moment

### ISSUE THREAD

**Issue by rramstad833** [Manuel-777/MTG-Arena-Tool#370]
Hi, I've tried 2.50, 2.5.6, 2.5.7 with no luck.

I always get the Loading Just a moment screen and it never progresses.

When I updated to 2.5.0 through the app automatically, I wasn't getting the deck / draft overlay, it would show up but no cards would be displayed.

I enabled beta channel and then this started happening.  Subsequently I have manually installed three different versions, listed above, and got the same behavior.

2.5.7 right now shows this error:

Uncaught Error: Cannot find module 'lodash'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602)
    at Function.Module._resolveFilename (C:\Users\rramstad\AppData\Local\Programs\MTG-Arena-Tool\resources\electron.asar\common\reset-search-paths.js:35)
    at Function.Module._load (internal/modules/cjs/loader.js:528)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
    at renderer.js:36

**Comment by rramstad833** [comment]
FYI, uninstalling completely and reinstalling from 2.5.7 gives exactly the same behavior.

**Comment by rramstad833** [comment]
I'm running Windows 10 and I had no problems with earlier versions of the program...  been running it for some time actually, many months.

**Comment by rramstad833** [comment]
Uninstalling the previous version and installing 2.5.9 allows me to get past the loading screen.

I haven't tested anything else but at least it's parsing the log now.

**Comment by Manuel-777** [comment]
Let me know if its working now! The issues you mentioned should have been up yesterday but the release did not get pushed.

**Comment by rramstad833** [comment]
Yes. it seems to be working now. Thanks.
